# SPDX-FileCopyrightText: 2023-2025 Jonas Tobias Hopusch <git@jotoho.de>
# SPDX-License-Identifier: CC0-1.0

name: 'Process Github Threads'

on:
  schedule:
    - cron: '0 0 * * *'
  issues:
    types: [assigned, milestoned]
  pull_request:
    types: [assigned, milestoned]

jobs:
  stale:
    name: Process stale threads
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      discussions: write
    concurrency:
      group: stale
      cancel-in-progress: true
    steps:
      - uses: actions/stale@v9.1.0
        with:
          exempt-all-assignees: true
          exempt-all-milestones: true
          stale-issue-message: "There has been no activity on this issue in a while, and it is not scheduled for remediation. If this continues, the issue will be closed."
          stale-pr-message: "There has been no activity on this pull request in a while, and it is not scheduled to be considered for merge. If this continues, the pull request will be closed."
  lockthreads:
    name: Scan and Lock closed threads
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    permissions:
      issues: write
      pull-requests: write
      discussions: write
    concurrency:
      group: lockthreads
      cancel-in-progress: true
    steps:
      - uses: dessant/lock-threads@v5.0.1
        with:
          issue-inactive-days: '28'
          pr-inactive-days: '28'
          discussion-inactive-days: '28'
