# SPDX-FileCopyrightText: 2023-2026 Jonas Tobias Hopusch <git@jotoho.de>
# SPDX-License-Identifier: CC0-1.0

name: 'Process Github Threads'

on:
  issues:
    types: [created, assigned, unassigned, milestoned, demilestoned]
  issue_comment:
    types: [created]
  pull_request:
    types: [created, assigned, unassigned, milestoned, demilestoned]
  pull_request_review:
    types: [submitted]
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  stale:
    name: Process stale threads
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
      discussions: write
    concurrency:
      group: stale
    steps:
      - uses: actions/stale@v10.3.0
        with:
          exempt-all-assignees: true
          exempt-all-milestones: true
          stale-issue-message: "There has been no detected activity on this issue in a while, it is not scheduled for remediation and it has not been assigned to anyone. If that continues, this issue will be automatically closed."
          stale-pr-message: "There has been no detected activity on this pull request in a while, it is not scheduled to be considered for merging and it has not been assigned to anyone. If that continues, this pull request will be automatically closed."
  lockthreads:
    name: Scan and Lock closed threads
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
      discussions: write
    concurrency:
      group: lockthreads
    steps:
      - uses: dessant/lock-threads@v6.0.2
        with:
          issue-inactive-days: '28'
          pr-inactive-days: '28'
          discussion-inactive-days: '28'
